### ISSUE TITLE
Error in alanine_dipeptide_mstis_bootstrap.ipynb

### ISSUE THREAD

**Issue by bolhuis** [openpathsampling/openpathsampling#507] opened 2016-06-28 14:17 UTC
When running this notebook error occurs when creating inter core trajectories at step/cell 40:

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-40-79f854d66f52> in <module>()
      7         try:
      8             count += 1
----> 9             tt = engine_high.generate_forward(tt[-1].reversed, core2core)
     10             storage.save(tt)
     11 

/Users/bolhuis/git/openpathsampling/openpathsampling/engines/dynamics_engine.pyc in generate_forward(self, snapshot, ensemble)
    236         """
    237 
--> 238         return self.generate(snapshot, ensemble.can_append, direction=+1)
    239 
    240     def generate_backward(self, snapshot, ensemble):

/Users/bolhuis/git/openpathsampling/openpathsampling/engines/dynamics_engine.pyc in generate(self, snapshot, running, direction)
    311 
    312             # Do integrator x steps
--> 313             snapshot = self.generate_next_frame()
    314             frame += 1
    315             if frame % log_freq == 0:

/Users/bolhuis/git/openpathsampling/openpathsampling/engines/openmm/engine.pyc in generate_next_frame(self)
    241         self.simulation.step(self.nsteps_per_frame)
    242         self._current_snapshot = None
--> 243         return self.current_snapshot
    244 
    245     def minimize(self):

/Users/bolhuis/git/openpathsampling/openpathsampling/engines/dynamics_engine.pyc in __getattr__(self, item)
    164     def __getattr__(self, item):
    165         # default is to look for an option and return it's value
--> 166         return self.options[item]
    167 
    168     @property

KeyError: 'current_snapshot'
```

This was running after I did a conda update --all

**Comment by dwhswenson** [comment] 2016-07-06 16:53
FWIW, I just verified that I get the same error when I run this notebook. Labelling this as "bug".

**Comment by jhprinz** [comment] 2016-07-08 07:02
I will look into this. Note that there is a very strange thing with accessing attributes defined by properties in python:

If you access an _computed_ attribute that is defined using `@property` and a function then, if there is an error in the execution of the property function python by default returns a KeyError on the property and not the real error that occurred!

So you (or me) have to look inside the `current_snapshot` property funtion of the engine used and see why it cannot return the current snapshot. I presume there is something going wrong with OpenMM. Not sure

**Comment by dwhswenson** [comment] 2016-07-08 10:53
> Note that there is a very strange thing with accessing attributes defined by properties in python:

No, this isn't Python. This is because you defined `__getattr__` to check a dictionary if no other attribute was found, and then don't transform the raised error into an `AttributeError`. I fixed this in the external engine PR: https://github.com/openpathsampling/openpathsampling/pull/144/files#diff-1f3c9e17b65986c77f91c9aefb7674d2; I can make a quick PR of the same text if you'd like.

**Comment by jhprinz** [comment] 2016-07-08 11:26
This was just a quick note that I thought about since I had some problems with descriptors that are interpreted wrong under some circumstances. This rare case applies here, I think:

If you try to access a descriptor (like `.current_snapshot`) which is defined using `@property` this will call the `__get__` method of the descriptor first. If that fails with an `AttributeError` !! which is the same error, if the attribute would not exist or `__get__` is not implemented. Then (and only for AttributeErrors), the __getattribute__ will call `__getattr__` as a fallback. Which is happening in this case and then fails because of `current_snapshot` not being in `self.options`. It should have been an `AttributeError` in the descriptor instead but these two cases are indistinguishable. 

Bottomline is: You can partially fix it the way you said, but if, for some reason the property fails with an AttributeError you will catch the error in `__getattr__` and report falsely that the property is missing and not in options. That is wrong.

I had this before and it took me several hours to realize what is happening. Here a short example.

```py
class A(object):
    @property
    def b(self):
        obj = object()
        return obj.b

    def __getattr__(self, item):
        # If there was an error in `p` I cannot see it here
        # Do something else without knowing about failing in `p`
        raise AttributeError('There is no attribute %s' % item)

a = A()
# access well defined propery `p`
a.p
```

There is no way to fix this other than to surround your property code (inside the property) with a try except clause and catch AttributeErrors and raise another error to report what is actually happening. 

The simpler way would be to look into `current_snapshot` and try to fix it there. That was my original suggestion. Hope that clarifies my earlier post. 

Still, what you suggest makes sense to have so please make a PR and add that.

**Comment by dwhswenson** [comment] 2016-07-08 13:22
The thing I was talking about wasn't intended to fix the problem @bolhuis was having. It does not prevent the error. However, it *does* fix the problem that the error is reporting itself as the incorrect type: there's an `AttributeError`, absolutely not a `KeyError`. As you said, if `__getattr__` is being called at all, the issue is that an `AttributeError` has been raised.

I'll go ahead and open a PR for that; tests on the external engine required the correct error type to be raised, which is why I implemented it over there in the first place.

The main problem of this issue, however, isn't that the error was a `KeyError`. It's that it was an error at all. (It's after running for quite a while, and it only seems to happen in that notebook).

> There is no way to fix this other than to surround your property code (inside the property) with a try except clause and catch AttributeErrors and raise another error to report what is actually happening.

Not perfect, but:

```python
class A(object):
    @property
    def bad_property(self):
        obj = object()
        return obj.b

    @property
    def good_property(self):
        return 1

    def __getattr__(self, item):
        if item in self.__class__.__dict__:
            # we should have this attribute
            p = self.__class__.__dict__[item]
            if isinstance(p, property):
                try:
                    result = p.fget(self)
                except:
                    raise
                else:
                    return result
            raise AttributeError("Something went wrong with " + str(item))
        else:
            raise AttributeError("I've never heard of " + str(item))

a = A()
a.bad_property
#---------------------------------------------------------------------------
#AttributeError                            Traceback (most recent call last)
#<ipython-input-3-796e4ba031a2> in <module>()
#----> 1 a.bad_property
#
#/Users/dwhs/example.py in __getattr__(self, item)
#     15             if isinstance(p, property):
#     16                 try:
#---> 17                     result = p.fget(self)
#     18                 except:
#     19                     raise
#
#/Users/dwhs/example.py in bad_property(self)
#      3     def bad_property(self):
#      4         obj = object()
#----> 5         return obj.b
#      6
#      7     @property
#
#AttributeError: 'object' object has no attribute 'b'

a.does_not_exist

#---------------------------------------------------------------------------
#AttributeError                            Traceback (most recent call last)
#<ipython-input-4-11b640528e00> in <module>()
#----> 1 a.does_not_exist
#
#/Users/dwhs/example.py in __getattr__(self, item)
#     22             raise AttributeError("Something went wrong with " + str(item))
#     23         else:
#---> 24             raise AttributeError("I've never heard of " + str(item))
#     25
#
#AttributeError: I've never heard of does_not_exist
```

How about I modify the code from external engine to do something like that? I'm not sure how to generate a test for the case of "Something went wrong with item" (and the test case for returning a successful result will also be weird.)

**Comment by jhprinz** [comment] 2016-07-08 16:58
Nice solution, that should do it. Go ahead with a PR to fix it.

**Comment by jhprinz** [comment] 2016-07-12 23:34
#516 should have fixed the wrong error message. So, if the error appears again, please let me know. I assume it will be from using `1000K` as high temperature for the first initial trajectory. A stepsize of `2fs` could be too large.

**Comment by jhprinz** [comment] 2016-07-13 14:45
I found the error (I presume). Problem is to run at high temperatures with stepwise of 2fs. This explodes at some point and there are NaN everywhere. OpenMM throws a 
```
AttributeError: 'module' object has no attribute 'Dataframe'
```

error which is the source of the Attribute confusion.

I replaced `2fs` with `1fs` used `1000K` and doubled the steps for OPS. Effectively having the same saving time_steps of 40fs now.

I assume this does not happen in other notebooks because we use low temperatures or the simulation is too short for this to happen.

**Comment by jhprinz** [comment] 2016-08-02 07:04
I think we can close this. The wrong error message is solved and the origin of the error was a bad setup.

**Comment by jhprinz** [comment] 2016-09-18 22:06
I think this was fixed by fixing the NaN problem.

**Closed by jhprinz** 2016-09-18 22:06 UTC
Labels: bug, closable?

**Comment by dwhswenson** [comment] 2016-09-18 22:11
Do you find it disappearing with VVVR at `2.0 fs` step size? (I hope so!)
