### ISSUE TITLE
Bug in `shared_configurations`

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#546] opened 2016-08-05 14:45 UTC
I'm having a little trouble tracking down the exact conditions that cause this, but I'm finding a bug in `shared_configurations` based on the fact that `Trajectory.iter_proxies()` can return "Iterator() over list of `Snapshot` or `LoaderProxy`", as its docs describe.

Here's my understanding of the problem. I call `shared_configurations` (well, actually, I start at `shared_trajectory`). It calls `as_proxies`, which in turn calls `iter_proxies`.

Now, `shared_configurations` calls both `self.as_proxies()` and `other.as_proxies()`, and then does the set intersection of them. However, I'm seeing a case where `self` is returning snapshots, and `other` is returning proxies. This, of course, means the intersection is empty.

Changing `shared_configurations` to do:

```python
        if not time_reversal:
            print "self:"
            for s in set(self.as_proxies()): print s
            print "other:"
            for s in set(other.as_proxies()): print s
            print
            return set(self.as_proxies()) & set(other.as_proxies())
```

I get output:
```
self:
<openpathsampling.engines.toy.snapshot.ToySnapshot object at 0x10f8dcc10>
<openpathsampling.engines.toy.snapshot.ToySnapshot object at 0x10f8ae050>
<openpathsampling.engines.toy.snapshot.ToySnapshot object at 0x10f8dcd10>
(etc)
other:
<openpathsampling.netcdfplus.proxy.LoaderProxy object at 0x10f8e90f0>
<openpathsampling.netcdfplus.proxy.LoaderProxy object at 0x10f8e9370>
<openpathsampling.netcdfplus.proxy.LoaderProxy object at 0x10f8e91e0>
(etc)
```

I haven't made a minimal working example to cause this, but it is happening in https://github.com/dwhswenson/OPSPiggybacker/pull/10.

**Comment by jhprinz** [comment] 2016-08-07 23:45
Why is that a bug? Not in all cases you can have a proxy. So maybe it is just bad naming or you think the function is doing something other that you expect.

> This, of course, means the intersection is empty.

No, that depends. This actually should work because the comparison uses the uuid and it should be the same for both.

**Comment by dwhswenson** [comment] 2016-08-08 00:02
> Why is that a bug?

It is a bug because `shared_configurations` is giving the wrong answer. `self` and `other` share several frames, by construction. `self.as_proxies()` returns a list of `ToySnapshot`s. `other.as_proxies()` returns a list of `LoaderProxy`s. As a result, `self.shared_configurations(other)` gives an empty set. Before merging #517, the tests in OPSPiggybacker passed. Now they don't.

> This actually should work because the comparison uses the uuid and it should be the same for both.

I think sets are based on hashes. `__eq__` doesn't matter here.

An alternative would be to rewrite `shared_configurations` to forcibly use proxy objects (probably cheaper than forcing use of full snapshots).

**Comment by jhprinz** [comment] 2016-08-08 08:20
> It is a bug because shared_configurations is giving the wrong answer.

Okay, that was my question, because I could not tell why your first comment was a bug. This is the (from my view) expected behavior.

> self and other share several frames, by construction

Okay, then I could ask, if they really have the same snapshot then why does `as_proxies` return different objects.

> I think sets are based on hashes. __eq__ doesn't matter here.

Yes and no. Set are based first on `__hash__` and then on `__eq__`. 

> An alternative would be to rewrite shared_configurations to forcibly use proxy objects (probably cheaper than forcing use of full snapshots)

Well, `.as_proxies` should be named `as a list that could contain proxies`. Normally a user should never get hold of a proxy object. These are meant for internal usage, although in 98% of the cases a user would not realize that it is a proxy. They should behave the same as the original in any respect, also sets and hashes (if I implemented it correctly)

So, a trajectory when you load it contains only proxies that is fastest. When you generate a trajectory it does not and hence returning proxies is slower, that is why `as_proxies` just returns what is really in the trajectory. Similar to `list.__getitem__(trajectory, index)`

So, running a set of mixed snapshots and proxies should work as expected and return one one element (which could be the proxy or the full object) depending on which was first, but only one thould be there. If that does not work I need to check the hashes and __eq__ of both `BaseSnapshot` and `LoaderProxy`. 

Could you also post a quick explanation on how to generate the two trajectories and why one has proxies while the other does not?

**Comment by dwhswenson** [comment] 2016-08-08 10:12
> So, running a set of mixed snapshots and proxies should work as expected and return one one element (which could be the proxy or the full object) depending on which was first, but only one thould be there. If that does not work I need to check the hashes and eq of both `BaseSnapshot` and `LoaderProxy`.

This is exactly what is not working. Can you look into those and see if there's anything obviously weird there? Again, all of this worked before #517.

> Could you also post a quick explanation on how to generate the two trajectories and why one has proxies while the other does not?

*Quick* explanation on how to generate the trajectories: run the tests for OPSPiggybacker. :-P

Quick and ***useful*** explanation: Don't have one yet. That's what I meant when I said I didn't have a minimal example. I'll work more on that today, but I was hoping that the issue would make the bugfix obvious. (I already spent an afternoon trying to figure this out before posting the issue.) I'll comment again if I can get a working minimal example to demonstrate the problem.

**Comment by jhprinz** [comment] 2016-08-08 10:26
Quick reply. This is indeed NOT working correctly. I need to find a good way to make this work because the hash function is not trivial.

It might be that it worked before by accident. Not sure, but I know why it can fail now.

I will look at the Piggybacker and see if that helps.

Main point. If you use UUIDs then all is fine and can easily be fixed. If not, then loading a snapshot from storage by index will not allow to compare a snapshot to a full snapshot (which does not have an index stored). You can compare two proxies in that case. 

One of the problem is also that hashing using UUID even in the uuid case is not always used which is some specific handling of isinstance in python that I was not aware of. isinstance seems to compare using `type` and `.__class__` which is not the same in case of a proxy...

So I need to find a way to generate a working hash for proxy objects if they reference an object just by an integer and storage. Might bw that in case of integer indexing this will not work. Simple example. Store the same snapshot in two stores and load a proxy of these objects. These will never equal (unless we compare coordinates, etc...)

Need to think about this. But it can and should be fixed soon.

**Comment by dwhswenson** [comment] 2016-08-08 10:47
Note on running OPSPiggybacker tests: you should run (from the main directory, with `setup.py` in it)

```
python ops_piggybacker/tests/common_test_data.py
```

This is leftover from #489, and probably could be changed after #499 fixed that, but the workaround still works and I never bothered to switch it back.

**Comment by dwhswenson** [comment] 2016-08-08 10:53
Oh, and two more things:

* if looking at OPSPiggybacker, use branch `renamings`, which has already fixed some other renaming-related issues
* should I still be trying to create a minimal example? it sounds like you have enough of a sense of what the problem is that it would be better for me to work on other things

**Comment by jhprinz** [comment] 2016-08-08 10:54
No, don't bother about an example. I know what I have to do.

**Closed** 2016-08-11 10:00 UTC
Labels: bug
