### ISSUE TITLE
Add support for external CV computation (pyña)

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#259] opened 2015-05-15 15:43 UTC
[add more discussion here...]

**Comment by dwhswenson** [comment] 2015-05-15 20:37
Some start to the discussion: in our Skype call today, I mentioned to @jhprinz that I've been working on a package that summarizes the output from another program that analyzes the structure of DNA. We were discussion how to make an OPS-ready collective variable out of this. Although we discussed it in the context of this specific set of tools, I think it might represent a more general paradigm for generating order parameters which we should support.

My little project is [pyña](http://github.com/dwhswenson/pyna). It parses the output from the [Curves+](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2761274/) program into `pandas.Panels`, and then has a few conveniences for analysis.

Basically, the issue is this: Curves+ will analyze a snapshot, but it will gives *all* its analysis at once. You can't ask for just part of the analysis. Given that (1) it gives some of the best results for the groove widths, and (2) it would be a bit of a pain to reimplement its groove width algorithm, we'd rather just re-use what they do.

So how do we do that in OPS? Consider the following:

Assume that maybe you wanted 2 numbers out of the whole Curves dataset. Each of these is an OPS CV. In principle, the easiest thing is to run Curves once for each CV. That will work, but that will obviously be computationally wasteful, and probably pretty slow.

So the question becomes whether we can use the fact that I've already generated a `pandas.Panel` (well, technically several panels) and cache that result for use in later order parameters. Even taking the string output from Curves and caching that might be useful, but the point is to avoid re-running Curves for every CV.

I think this general approach of using an external program which calculates several collective variables (or at least extracts parts of what are needed for them) might be desired in a lot of specialized situations. It would be nice to have a clean way of handling that.

**Comment by jhprinz** [comment] 2015-11-11 14:57
I think this is now supported by the new storage...

**Comment by dwhswenson** [comment] 2016-01-21 00:16
Self-assigned as a reminder to implement a check. In Skype call with @jhprinz, we *think* this has been fully implemented.

**Comment by jhprinz** [comment] 2016-03-04 22:46
This is already implemented. Will close this now. You can define arbitrary value CVs and store these without caching. You can also design cached CVs that are dependent on other CVs.

**Comment by jhprinz** [comment] 2016-03-04 22:46
Can I close this?

**Comment by dwhswenson** [comment] 2016-03-05 06:49
Per https://github.com/choderalab/openpathsampling/issues/259#issuecomment-173409947, I'd rather not close it until there's a test in place for exactly what I was thinking to do.

**Comment by dwhswenson** [comment] 2020-10-14 16:26
This should have been closed when @jhprinz suggested it [on November 11, 2015](https://github.com/openpathsampling/openpathsampling/issues/259#issuecomment-155804521). Got to it a little less than 5 years overdue....

**Closed by dwhswenson** 2020-10-14 16:26 UTC
